-- =====================================================================
-- SportLK - MySQL 8.0 Complete Relational & Spatial Database Schema
-- Academic Year 2026 | SE5104 Mini Project | Group 13
-- Sabaragamuwa University of Sri Lanka
-- =====================================================================

CREATE DATABASE IF NOT EXISTS sportlk_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE sportlk_db;

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20) NULL,
  profile_image_url TEXT NULL,
  base_role ENUM('PLAYER', 'ADMIN') NOT NULL DEFAULT 'PLAYER',
  is_team_manager BOOLEAN NOT NULL DEFAULT FALSE,
  is_tournament_organizer BOOLEAN NOT NULL DEFAULT FALSE,
  active_workspace ENUM('PLAYER', 'TEAM_MANAGER', 'TOURNAMENT_ORGANIZER', 'ADMIN') NOT NULL DEFAULT 'PLAYER',
  account_status ENUM('ACTIVE', 'SUSPENDED', 'DEACTIVATED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. USER SPORTS INTERESTS TABLE
CREATE TABLE IF NOT EXISTS user_sports_interests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  sport_type ENUM('CRICKET', 'FUTSAL', 'BADMINTON', 'BASKETBALL') NOT NULL,
  skill_level ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL DEFAULT 'BEGINNER',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. ROLE APPLICATIONS TABLE
CREATE TABLE IF NOT EXISTS role_applications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  requested_role ENUM('TEAM_MANAGER', 'TOURNAMENT_ORGANIZER') NOT NULL,
  justification_notes TEXT NULL,
  supporting_document_url TEXT NULL,
  status ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  reviewed_by_admin_id BIGINT NULL,
  admin_feedback TEXT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. POSTS (COMMUNITY FEED)
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  author_id BIGINT NOT NULL,
  caption TEXT NOT NULL,
  media_url TEXT NULL,
  sport_tag VARCHAR(50) NULL,
  likes_count INT NOT NULL DEFAULT 0,
  comments_count INT NOT NULL DEFAULT 0,
  visibility ENUM('PUBLIC', 'TEAM_ONLY') NOT NULL DEFAULT 'PUBLIC',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. POST COMMENTS
CREATE TABLE IF NOT EXISTS post_comments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  comment_body TEXT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. POST LIKES
CREATE TABLE IF NOT EXISTS post_likes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_post_user_like (post_id, user_id),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. POST REPORTS
CREATE TABLE IF NOT EXISTS post_reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT NOT NULL,
  reporter_id BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status ENUM('PENDING', 'RESOLVED', 'DISMISSED') NOT NULL DEFAULT 'PENDING',
  handled_by_admin_id BIGINT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. TEAMS
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  manager_id BIGINT NOT NULL,
  team_name VARCHAR(100) NOT NULL UNIQUE,
  sport_type ENUM('CRICKET', 'FUTSAL', 'BADMINTON', 'BASKETBALL') NOT NULL,
  logo_url TEXT NULL,
  team_bio TEXT NULL,
  primary_location_city VARCHAR(100) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. TEAM MEMBERS
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  member_role ENUM('CAPTAIN', 'VICE_CAPTAIN', 'SQUAD_PLAYER') NOT NULL DEFAULT 'SQUAD_PLAYER',
  jersey_number INT NULL,
  joined_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_team_user_member (team_id, user_id),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. TEAM INVITATIONS
CREATE TABLE IF NOT EXISTS team_invitations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT NOT NULL,
  invited_user_id BIGINT NOT NULL,
  invite_type ENUM('MANAGER_TO_PLAYER', 'PLAYER_REQUEST_TO_JOIN') NOT NULL,
  status ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (invited_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. VENUES (SPATIAL)
CREATE TABLE IF NOT EXISTS venues (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  venue_name VARCHAR(150) NOT NULL,
  location_coordinates POINT NOT NULL SRID 4326,
  address_line VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  district VARCHAR(100) NULL,
  province VARCHAR(100) NULL,
  contact_phone VARCHAR(20) NULL,
  hourly_base_rate DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  SPATIAL INDEX sp_idx_venue_coordinates (location_coordinates)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. VENUE FACILITIES
CREATE TABLE IF NOT EXISTS venue_facilities (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  sport_type ENUM('CRICKET', 'FUTSAL', 'BADMINTON', 'BASKETBALL') NOT NULL,
  court_or_pitch_count INT NOT NULL DEFAULT 1,
  has_floodlights BOOLEAN NOT NULL DEFAULT FALSE,
  has_parking BOOLEAN NOT NULL DEFAULT FALSE,
  has_changing_rooms BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. TEAM CHALLENGES
CREATE TABLE IF NOT EXISTS team_challenges (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  challenger_team_id BIGINT NOT NULL,
  challenged_team_id BIGINT NOT NULL,
  venue_id BIGINT NULL,
  proposed_match_date DATETIME NOT NULL,
  sport_type ENUM('CRICKET', 'FUTSAL', 'BADMINTON', 'BASKETBALL') NOT NULL,
  status ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (challenger_team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (challenged_team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. PAYMENTS (PayHere transactions)
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  payhere_order_id VARCHAR(100) NOT NULL UNIQUE,
  payhere_payment_id VARCHAR(100) NULL,
  amount DECIMAL(10, 2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'LKR',
  payment_purpose ENUM('TOURNAMENT_REGISTRATION', 'VENUE_BOOKING') NOT NULL,
  payment_status ENUM('INITIATED', 'SUCCESSFUL', 'FAILED', 'CHARGEDBACK') NOT NULL DEFAULT 'INITIATED',
  md5_verification_signature VARCHAR(255) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 15. VENUE BOOKINGS
CREATE TABLE IF NOT EXISTS venue_bookings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  booked_by_user_id BIGINT NOT NULL,
  booking_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  total_price DECIMAL(10, 2) NOT NULL,
  booking_status ENUM('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'REFUNDED') NOT NULL DEFAULT 'PENDING_PAYMENT',
  payment_id BIGINT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
  FOREIGN KEY (booked_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 16. TOURNAMENTS
CREATE TABLE IF NOT EXISTS tournaments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  organizer_id BIGINT NOT NULL,
  venue_id BIGINT NULL,
  tournament_name VARCHAR(150) NOT NULL,
  sport_type ENUM('CRICKET', 'FUTSAL', 'BADMINTON', 'BASKETBALL') NOT NULL,
  tournament_format ENUM('KNOCKOUT_SINGLE', 'ROUND_ROBIN', 'GROUP_AND_KNOCKOUT') NOT NULL DEFAULT 'KNOCKOUT_SINGLE',
  max_participating_teams INT NOT NULL DEFAULT 16,
  registration_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  tournament_status ENUM('DRAFT', 'OPEN_FOR_REGISTRATION', 'ONGOING', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (organizer_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 17. TOURNAMENT REGISTRATIONS
CREATE TABLE IF NOT EXISTS tournament_registrations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tournament_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  payment_id BIGINT NULL,
  registration_status ENUM('PAYMENT_PENDING', 'CONFIRMED', 'DISQUALIFIED') NOT NULL DEFAULT 'PAYMENT_PENDING',
  registered_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_tourney_team_reg (tournament_id, team_id),
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 18. MATCHES
CREATE TABLE IF NOT EXISTS matches (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tournament_id BIGINT NULL,
  home_team_id BIGINT NOT NULL,
  away_team_id BIGINT NOT NULL,
  venue_id BIGINT NULL,
  scheduled_start_time DATETIME NOT NULL,
  match_status ENUM('SCHEDULED', 'LIVE', 'COMPLETED', 'ABANDONED', 'POSTPONED') NOT NULL DEFAULT 'SCHEDULED',
  winner_team_id BIGINT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL,
  FOREIGN KEY (home_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  FOREIGN KEY (away_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL,
  FOREIGN KEY (winner_team_id) REFERENCES teams(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 19. TOURNAMENT BRACKETS
CREATE TABLE IF NOT EXISTS tournament_brackets (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tournament_id BIGINT NOT NULL,
  round_number INT NOT NULL,
  match_sequence_in_round INT NOT NULL,
  match_id BIGINT NULL,
  next_bracket_id BIGINT NULL,
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
  FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 20. MATCH SCORES (Dynamic JSON scorecard for live events)
CREATE TABLE IF NOT EXISTS match_scores (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  match_id BIGINT NOT NULL UNIQUE,
  home_team_score_display VARCHAR(100) NULL,
  away_team_score_display VARCHAR(100) NULL,
  detailed_scorecard_json JSON NULL,
  last_updated_by_user_id BIGINT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 21. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipient_id BIGINT NOT NULL,
  notification_title VARCHAR(150) NOT NULL,
  notification_body TEXT NOT NULL,
  notification_type ENUM('MATCH_ALERT', 'SCORE_UPDATE', 'CHALLENGE_RECEIVED', 'PAYMENT_RECEIPT', 'SYSTEM') NOT NULL DEFAULT 'SYSTEM',
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
